{{ if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "covid-germany-exporter.fullname" . }}
  labels:
  {{- include "covid-germany-exporter.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.labels }}
  {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - honorLabels: true
    targetPort: http-metrics
    {{- with .Values.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "covid-germany-exporter.selectorLabels" . | nindent 6 }}
{{- end }}
