apiVersion: v1
kind: Service
metadata:
  name: {{ include "covid-germany-exporter.fullname" . }}
  labels:
    {{- include "covid-germany-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "covid-germany-exporter.selectorLabels" . | nindent 4 }}
