name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub docker registry
        uses: docker/login-action@v1
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }

      - name: Builder docker container
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64/v8,linux/amd64 \
            --tag ghcr.io/noizeme/prometheus-covid-exporter/prometheus-covid-exporter:latest \
            .
