name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub repository
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Builder docker container
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64/v8,linux/amd64 \
            --tag docker.pkg.github.com/noizeme/prometheus-covid-exporter/prometheus-covid-exporter:latest \
            .
